name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: 📥 Checkout do repositório
      uses: actions/checkout@v3

    - name: 📦 Setup do Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: 📚 Instalar dependências
      run: npm ci

    - name: 🗃 Criar pasta do banco de dados
      run: mkdir -p bd

    - name: 🧱 Inicializar banco SQLite com schema.sql
      run: sqlite3 ./bd/esmforum.db < ./bd/schema.sql

    - name: ✅ Rodar testes
      run: npm test
